#! /bin/bash

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function editstuff()
{
clear
echo -e "Edit what?"
select editchoice in bashrc rebash apt-history createpass forcefontfsck installreqs julian lagging pressanykey tasklist testfunction webterm welcome editstuff
do
	case "$editchoice" in
		"bashrc")
			clear
			echo -e "Edit .bashrc in:?"
			select basheditchoice in nano kate
				do
					case "$basheditchoice" in
						"nano")
							nano ~/.bashrc
						return
						;;
						"kate")
							kate ~/.bashrc
						return
						;;
					esac
				done
				return
			;;
		"rebash")
			clear
			echo -e "Edit .bashrc in:?"
			select basheditchoice in nano kate
				do
					case "$basheditchoice" in
						"nano")
							nano ~/BASH/rebash
						return
						;;
						"kate")
							kate ~/BASH/rebash
						return
						;;
					esac
				done
				return
			;;
		"apt-history")
			clear
			echo -e "Edit apt-history script in:?"
			select historyeditchoice in nano kate
				do
					case "$historyeditchoice" in
						"nano")
							nano ~/BASH/apt-history
						return
						;;
						"kate")
							kate ~/BASH/apt-history
						return
						;;
					esac
				done
				return
			;;
		"createpass")
			clear
			echo -e "Edit createpass script in:?"
			select passeditchoice in nano kate
				do
					case "$passeditchoice" in
						"nano")
							nano ~/BASH/createpass
						return
						;;
						"kate")
							kate ~/BASH/createpass
						return
						;;
					esac
				done
				return
			;;
		"forcefontfsck")
			clear
			echo -e "Edit forcefontfsck script in:?"
			select forceeditchoice in nano kate
				do
					case "$forceeditchoice" in
						"nano")
							nano ~/BASH/forcefontfsck
						return
						;;
						"kate")
							kate ~/BASH/forccefontfsck
						return
						;;
					esac
				done
				return
			;;
		"installreqs")
			clear
			echo -e "Edit the installreqs script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/installreqs
							return
							;;
						"kate")
							kate ~/BASH/installreqs
							return
							;;
					esac
				done
				return
			;;
		"julian")
			clear
			echo -e "Edit Julian time function in:?"
			select julianeditchoice in nano kate
				do
					case "$julianeditchoice" in
						"nano")
							nano ~/BASH/juliantime
							return
							;;
						"kate")
							kate ~/BASH/juliantime
							return
							;;
					esac
				done
				return
			;;
		"lagging")
			clear
			echo -e "Edit the lag script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/lagging
							return
							;;
						"kate")
							kate ~/BASH/lagging
							return
							;;
					esac
				done
				return
			;;
		"pressanykey")
			clear
			echo -e "Edit the lag script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/pressanykey
							return
							;;
						"kate")
							kate ~/BASH/pressanykey
							return
							;;
					esac
				done
				return
			;;
		"tasklist")
			clear
			echo -e "Edit Tasklist in:?"
			select taskeditchoice in nano kate
				do
					case "$taskeditchoice" in
						"nano")
							nano ~/BASH/Tasklist
							return
							;;
						"kate")
							kate ~/BASH/Tasklist
							return
							;;
					esac
				done
				return
			;;
		"testfunction")
			clear
			echo -e "Edit the testfunction script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/testfunction
							return
							;;
						"kate")
							kate ~/BASH/testfunction
							return
							;;
					esac
				done
				return
			;;
		"webterm")
			clear
			echo -e "Edit the webterm script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/webterm
							return
							;;
						"kate")
							kate ~/BASH/webterm
							return
							;;
					esac
				done
				return
			;;
		"welcome")
			clear
			echo -e "Edit Welcome script in:?"
			select welcomeeditchoice in nano kate
				do
					case "$welcomeeditchoice" in
						"nano")
							nano ~/BASH/welcome1
						return
						;;
						"kate")
							kate ~/BASH/welcome1
						return
						;;
					esac
				done
				return
			;;
		"editstuff")
			clear
			echo -e "Edit the editstuff script in:?"
			select editeditchoice in nano kate
				do
					case "$editeditchoice" in
						"nano")
							nano ~/BASH/editstuff
							return
							;;
						"kate")
							kate ~/BASH/editstuff
							return
							;;
					esac
				done
				return
			;;
	esac
done
}
