#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function installreqs()
{
clear
echo -e "Multiple functions are available to you. Do you want to: (select one)\nInstall PPA's into system.\nInstall required programs."
select installreqschoice in "Add PPAs" "Install Programs"
do
	case "$installreqschoice" in
		"Add PPAs")
			clear
			echo "Adding Ubuntu Wine PPA to your system."
			sudo add-apt-repository ppa:ubuntu-wine/ppa
			clear
			echo "Adding JDownloader PPA to your system."
			sudo add-apt-repository ppa:jd-team/jdownloader
			clear
			echo "Adding Chromium Daily Stable to your system."
			sudo add-apt-repository ppa:chromium-daily/stable
			clear
			echo "Adding "
			sudo add-apt-repository ppa:pipelight/stable
			sudo apt-get update
		return
		;;
		"Install Programs")
			clear
			echo -e "Adding a few programs onto your system."
			case $mintVersion in
				*"KDE"*)
				sudo apt-get install curl fortunes fortune-mod fortunes-spam fortunes-bofh-excuses tilda finch konversation kuser namebench ubuntu-restricted-extras ubuntu-restricted-addons
				;;
				*"Cinnamon"*)
				sudo apt-get install curl fortunes fortune-mod fortunes-spam fortunes-bofh-excuses tilda finch pidgin namebench ubuntu-restricted-extras ubuntu-restricted-addons
				;;
			esac
		return
		;;
	esac
done
}
