#! /bin/bash

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function installbashscript()
{
cd
wget https://raw.github.com/cypher-neo/nanosecond/master/.bashrc -O .bashrc
mkdir ~/BASH/
cd ~/BASH/
wget https://raw.github.com/cypher-neo/nanosecond/master/LICENSE -O LICENSE
wget https://raw.github.com/cypher-neo/nanosecond/master/Tasklist -O Tasklist
wget https://raw.github.com/cypher-neo/nanosecond/master/apt-history -O apt-history
wget https://raw.github.com/cypher-neo/nanosecond/master/createpass -O createpass
wget https://raw.github.com/cypher-neo/nanosecond/master/editstuff -O editstuff
wget https://raw.github.com/cypher-neo/nanosecond/master/forcefontfsck -O forcefontfsck
wget https://raw.github.com/cypher-neo/nanosecond/master/installreqs -O installreqs
wget https://raw.github.com/cypher-neo/nanosecond/master/juliantime -O juliantime
wget https://raw.github.com/cypher-neo/nanosecond/master/lagging -O lagging
wget https://raw.github.com/cypher-neo/nanosecond/master/rebash -O rebash
wget https://raw.github.com/cypher-neo/nanosecond/master/webterm -O webterm
wget https://raw.github.com/cypher-neo/nanosecond/master/welcome1 -O welcome1
clear
source ~/.bashrc
}

installbashscript
