#!/bin/bash

#########################################################################################################
#              			The Modified Julian RealTime Clock					#
# Modified Julian Date can be read about at http://en.wikipedia.org/wiki/Julian_day			#
#													#
# I first became fascinated with Modified Julian Time Date while writing a novella that can be read at	#
# http://fav.me/d4srzzh.					                                        #
#													#
# This realtime clock converts the current date to Modified JD and displays both in realtime.		#
# When I removed the sleep function, it confirmed accurate down to the nanosecond			#
#########################################################################################################

function juliantime()
{
t=1
	while [ -n "$t" ] 
    		do
    			todayis=$(date +"%F")
    			let julian=(`date +%s -d $todayis`-`date +%s -d 1968-05-24`)/86400+40000
    			hourtime=$(date +"%H")
    			minutetime=$(date +"%M")
    			secondtime=$(date +"%S.%N" | head -c6)
    			juliantime=$(echo "scale=9; ($hourtime / 24) + ($minutetime / 1440) + ($secondtime / 86400)" | bc -l)
    			clear
    			echo -e "Standard Gregorian Date\n${BRed}$todayis${Color_Off} ${BRed}$hourtime${Color_Off}:${BRed}$minutetime${Color_Off}:${BRed}$secondtime${Color_Off}\n\nModified Julian\n${BBlue}$julian$juliantime${Color_Off}"
    			sleep 0.001
			t=1 # This creates an infinite loop. Ctrl-Z to abort, or just Alt-F4 to close the entire Terminal window
    done
}
