#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

########################
# Restart/Refresh BASH #
########################

function rebash()
{
select rebashchoice in "With APT Update" "Without APT Update"
do
	case "$rebashchoice" in
		"With APT Update")
			echo -e "${Yellow}First, I'll update the APT repositories.${Color_Off}"
			sleep 2s
			sudo apt-get update
			clear
			echo -e "${Yellow}Now, I'll reset BASH for you.${Color_Off}"
			sleep 2s
			clear
			source ~/.bashrc
		return
		;;
		"Without APT Update")
			echo -e "${Yellow}I'll reset BASH for you.${Color_Off}"
			sleep 2s
			clear
			source ~/.bashrc
		return
		;;
	esac
done
}
