#! /bin/bash/

function tradersdisplay()
{
clear
echo -e "Item\t\tLow\tHigh\nSalt\t\t$saltlow\t$salthigh\nTea\t\t$tealow\t$teahigh\nWine\t\t$winelow\t$winehigh\nAmber\t\t$amberlow\t$amberhigh\nOil\t\t$oillow\t$oilhigh\nWeapons\t\t$weaponslow\t$weaponshigh\nParchment\t\t$parchmentlow\t$parchmenthigh\nIndigo\t\t$indigolow\t$indigohigh\n\nCONTRABAND\nRugs\t\t$rugslow\t$rugshigh\nGunpowder\t\t$gunpowderlow\t$gunpowderhigh"
pressanykey
tradewind
}

function tradewind()
{
saltcurrent="0"
teacurrent="0"
winecurrent="0"
ambercurrent="0"
oilcurrent="0"
weaponscurrent="0"
parchmentcurrent="0"
indigocurrent="0"
rugscurrent="0"
gunpowdercurrent="0"
clear
echo -e "Enter the current prices"
echo "Salt Price"
read saltcurrent
if [ $saltlow = "" ]; then saltlow=($saltcurrent);fi
if [ $salthigh = "" ]; then salthigh=($saltcurrent);fi
if [ $saltcurrent > $salthigh ]; then salthigh=($saltcurrent);fi
if [ $saltcurrent < $saltlow ]; then saltlow=($saltcurrent);fi
echo "Tea Price"
read teacurrent
if [ "$tealow" = "" ]; then tealow=($teacurrent);fi
if [ "$teahigh" = "" ]; then teahigh=($teacurrent);fi
if [ "$teacurrent" > "$teahigh" ]; then teahigh=($teacurrent);fi
if [ "$teacurrent" < "$tealow" ]; then tealow=($teacurrent);fi
echo "Wine Price"
read winecurrent
if [ "$winelow" = "" ]; then winelow=($winecurrent);fi
if [ "$winehigh" = "" ]; then winehigh=($winecurrent);fi
if [ "$winecurrent" > "$winehigh" ]; then winehigh=($winecurrent);fi
if [ "$winecurrent" < "$winelow" ]; then winelow=($winecurrent);fi
echo "Amber Price"
read ambercurrent
if [ "$amberlow" = "" ]; then amberlow=($ambercurrent);fi
if [ "$amberhigh" = "" ]; then amberhigh=($ambercurrent);fi
if [ "$ambercurrent" > "$amberhigh" ]; then amberhigh=($ambercurrent);fi
if [ "$ambercurrent" < "$amberlow" ]; then amberlow=($ambercurrent);fi
echo "Oil Price"
read oilcurrent
if [ "$oillow" = "" ]; then oillow=($oilcurrent);fi
if [ "$oilhigh" = "" ]; then oilhigh=($oilcurrent);fi
if [ "$oilcurrent" > "$oilhigh" ]; then oilhigh=($oilcurrent);fi
if [ "$oilcurrent" < "$oillow" ]; then oillow=($oilcurrent);fi
echo "Weapons Price"
read weaponscurrent
if [ "$weaponslow" = "" ]; then weaponslow=($weaponscurrent);fi
if [ "$weaponshigh" = "" ]; then weaponshigh=($weaponscurrent);fi
if [ "$weaponscurrent" > "$weaponshigh" ]; then weaponshigh=($weaponscurrent);fi
if [ "$weaponscurrent" < "$weaponslow" ]; then weaponslow=($weaponscurrent);fi
echo "Parchment Price"
read parchmentcurrent
if [ "$parchmentlow" = "" ]; then parchmentlow=($parchmentcurrent);fi
if [ "$parchmenthigh" = "" ]; then parchmenthigh=($parchmentcurrent);fi
if [ "$parchmentcurrent" > "$parchmenthigh" ]; then parchmenthigh=($parchmentcurrent);fi
if [ "$parchmentcurrent" < "$parchmentlow" ]; then parchmentlow=($parchmentcurrent);fi
echo "Indigo Price"
read indigocurrent
if [ "$indigolow" = "" ]; then indigolow=($indigocurrent);fi
if [ "$indigohigh" = "" ]; then indigohigh=($indigocurrent);fi
if [ "$indigocurrent" > "$indigohigh" ]; then indigohigh=($indigocurrent);fi
if [ "$indigocurrent" < "$indigolow" ]; then indigolow=($indigocurrent);fi
echo "Rugs Price"
read rugscurrent
if [ "$rugslow" = "" ]; then rugslow=($rugscurrent);fi
if [ "$rugshigh" = "" ]; then rugshigh=($rugscurrent);fi
if [ "$rugscurrent" > "$rugshigh" ]; then rugshigh=($rugscurrent);fi
if [ "$rugscurrent" < "$rugslow" ]; then rugslow=($rugscurrent);fi
echo "Gunpowder Price"
read gunpowdercurrent
if [ "$gunpowderlow" = "" ]; then gunpowderlow=($gunpowdercurrent);fi
if [ "$gunpowderhigh" = "" ]; then gunpowderhigh=($gunpowdercurrent);fi
if [ "$gunpowdercurrent" > "$gunpowderhigh" ]; then gunpowderhigh=($gunpowdercurrent);fi
if [ "$gunpowdercurrent" < "$gunpowderlow" ]; then gunpowderlow=($gunpowdercurrent);fi
tradersdisplay
}
