#! /bin/bash/

function tradedisplay()
{
	clear
	format="%10s\t%10s\t%10s\n"
	printf "$format" "Item" "Low" "High"
	printf "$format" "====" "===" "===="
	for (( i = 0 ; i < ${#item[@]} ; i++ ))
	do
		printf "$format" ${item[$i]} ${low[$i]} ${high[$i]}
	done
	read -n1 -sp "Press any key to continue, or CTRL+C to quit."
}

function getPrice(){
	for (( i = 0 ; i < ${#item[@]} ; i++ ))
	do
		read -p "Price of ${item[$i]}: " current[$i]
		if [[ ${low[$i]} == ${item[$i]} ]]; then low[$i]=${current[$i]};fi
		if [[ ${high[$i]} == ${item[$i]} ]]; then high[$i]=${current[$i]};fi
		if [[ current[$i] > high[$i] ]]; then high[$i]=${current[$i]};fi
		if [[ current[$i] < low[$i] ]]; then low[$i]=${current[$i]};fi
	done
}

# MAIN PROGRAM
declare -a item=(Salt Tea Wine Amber Oil Weapons Parchment Indigo Rugs Gunpower)
declare -a low=(${item[@]})
declare -a current=(${item[@]})
declare -a high=(${item[@]})
while :
do
	clear
	echo -e "Enter the current prices"
	getPrice "${item[@]}"
	tradedisplay
done
