#! /bin/bash/

#########################COPYRIGHT NOTICE################################
#Copyright (C) 2013 cypher-neo (github.com/cypher-neo)			#
#									#
#This program is free software; you can redistribute it and/or		#
#modify it under the terms of the GNU General Public License		#
#as published by the Free Software Foundation; either version 2		#
#of the License, or (at your option) any later version.			#
#									#
#This program is distributed in the hope that it will be useful,	#
#but WITHOUT ANY WARRANTY; without even the implied warranty of		#
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		#
#GNU General Public License for more details.				#
#									#
#You should have received a copy of the GNU General Public License	#
#along with this program; if not, write to the				#
#Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,	#
#Boston, MA  02110-1301, USA.#						#
#########################################################################

function webterm()
{
clear
echo -e "Where do you wish to go?"
select webchoice in internet IRC
do
	case "$webchoice" in
		"internet")
			clear
			echo "Enter what page you wish to surf to."
			read webaddress
				echo "What program do you want to access the internet with?"
				select internetchoice in chromium elinks links2
				do
					case "$internetchoice" in
						"chromium")
							chromium-browser $webaddress
						return
						;;
						"elinks")
							elinks $webaddress
						return
						;;
						"links2")
							links2 $webaddress
						return
						;;
					esac
				done
				return
			;;
		"IRC")
			clear
				echo "What program should I use to access the IRC?"
				select ircchoice in finch
					do
						case "$ircchoice" in
							"finch")
								finch
							return
							;;
						esac
					done
					return
				;;
	esac
done
}
