#! /bin/bash/
function welcome1()
{
# who am i?
username=$(whoami)
ontime=$(uptime | sed 's/^[^u]*up  *\([^,]*\),.*/\1/')

#The Welcome Array - With included quotes from The Roguelet's ABC and some pickup lines
#Some random quotes and a pickup line
declare -a RANDARRAYONE=("Think honk if you're a telepath." "Of all the things I've ever lost, I miss my mind the most." "I am not the Lorax. I speak only for myself." "I will acknowledge rewards for they are my due; yet I will welcome obstacles for they are my challenge." "If you want me to fall for you $username, you better give me something worth tripping for.")
randline1=${RANDARRAYONE[RANDOM % ${#RANDARRAYONE[*]}]}
#Some quotes from The Roguelet's ABC
declare -a RANDARRAYTWO=("Flitter flutter in the air, How I wonder why you're there? Chasing bats is not much fun - The worst is when you're killed by one." "See that funny little man, Try and catch him if you can. Quickly now! That's too slow - Where did all your money go?" "Think again before you try, to impale a floating eye. If you miss it with your sword, You may soon be very bored." "If a 'goblin (hob) waylays you, slice him up before he slays you. Nothing makes you look a slob, Like running from a hob'lin (gob)" "One big monster, he called troll. He don't rock and he don't roll, Drink no wine and smoke no stogies; He just love to eat them roguies.")
randline2=${RANDARRAYTWO[RANDOM % ${#RANDARRAYTWO[*]}]}


hour=$(date +"%H")
declare -a EARLYARRAY=("Have you gotten a life yet $username?" "Its really VERY late!" "Got insomnia $username?" "Why are you waking me up $username?" "Getting an early start on the day?" "Do you realize what time it is $username?" "You probably shouldn't be drinking coffee at this time of the day $username." "$randline1" "$randline2")
declare -a MORNARRAY=("Whatever food, news, or images you internalize in the morning, will define the energy and perspective of your day. Choose wisely $username." "Good morning $username!" "Have a great morning $username!" "This is the beginning of a fine day." "Have you had your coffee yet this morning?" "Have a great day!" "$randline1" "$randline2")
declare -a LUNCHARRAY=("It's lunchtime!" "Are you going to eat something or just keeping typing?" "I hope you remembered to bring a lunch today." "Go have a cup of coffee $username and then get back to work refreshed." "$randline1" "$randline2")
declare -a AFTERARRAY=("Good afternoon $username!" "This looks like a great afternoon!" "Now that you've had a byte to eat, stop pounding on my keys so hard." "Welcome back, $username." "Have you had your afternoon cup of coffee yet $username?" "$randline1" "$randline2")
declare -a EVEARRAY=("Good evening $username!" "How did your day go today?" "I hope you are feeling well this evening." "Did you have a good day today $username?" "$randline1" "$randline2")

if [ $hour -ge 0 -a $hour -lt 7 ]; then
welcomeline=${EARLYARRAY[RANDOM % ${#EARLYARRAY[*]}]}
elif [ $hour -ge 7 -a $hour -lt 12 ]; then
welcomeline=${MORNARRAY[RANDOM % ${#MORNARRAY[*]}]}
elif [ $hour -ge 12 -a $hour -lt 13 ]; then
welcomeline=${LUNCHARRAY[RANDOM % ${#LUNCHARRAY[*]}]}
elif [ $hour -ge 13 -a $hour -lt 18 ]; then
welcomeline=${AFTERARRAY[RANDOM % ${#AFTERARRAY[*]}]}
elif [ $hour -ge 18 -a $hour -lt 22 ]; then
welcomeline=${EVEARRAY[RANDOM % ${#EVEARRAY[*]}]}
else
welcomeline=${EARLYARRAY[RANDOM % ${#EARLYARRAY[*]}]}
fi

taskline="${BRed}Task List${Color_Off}\n$(cat -n $HOME/BASH/Tasklist)"
fortuneline="${BRed}Random Fortune Cookie${Color_Off}\n$(fortune)"

if [ "$EASTEREGG" = "1" ]
then
fortuneline="${BYellow}Droid Search Results${Color_Off}\n${Color_Off}These are not the droids you are looking for.\nMove along. Nothing to see here.${Color_Off}"
EASTEREGG="0"
fi

#Welcome
echo -e "$welcomeline"
echo -e "This computer has been on for ${BRed}$ontime${Color_Off}."

#Tasklist
echo -e "\n$taskline"

#Fortune
echo -e "\n$fortuneline"
}
